# Nome del workflow che vedrai su GitHub
name: Deploy to Firebase Hosting

# Questo dice a GitHub di eseguire il workflow
# ogni volta che fai un push sul branch "main"
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    # Usa l'ultima versione di Ubuntu come sistema operativo
    runs-on: ubuntu-latest
    steps:
      # 1. Scarica il codice del tuo repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Installa le dipendenze e crea la versione di produzione del sito
      - name: Install dependencies and build
        run: npm ci && npm run build

      # 3. Fa il deploy su Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARCATEMPO_TCS }}'
          channelId: live   
          projectId: marcatempo-tcs